export type NanCell = "H" | { src: string };

/** 旧 nanpure.html の盤面（H = 入力マス） */
export const NANPURE_LAYOUT: NanCell[][] = [
  [
    "H",
    { src: "/images/mZjUp8tYWs6fHWae.png" },
    { src: "/images/dyT3ksKEBSB8Q4pt.png" },
    "H",
    "H",
    { src: "/images/fdrDDa-R-WTFpdtJ.png" },
    "H",
    "H",
    "H",
  ],
  [
    { src: "/images/7tH3ba-e74zEbr2B.png" },
    "H",
    "H",
    "H",
    { src: "/images/kxjuTJf3xAAe5yTf.png" },
    "H",
    { src: "/images/fdrDDa-R-WTFpdtJ.png" },
    "H",
    "H",
  ],
  [
    "H",
    "H",
    { src: "/images/FTKTbcjU_dSd4ELT.png" },
    { src: "/images/dyT3ksKEBSB8Q4pt.png" },
    { src: "/images/PauEnBcbXDSy-3GF.png" },
    "H",
    { src: "/images/7tH3ba-e74zEbr2B.png" },
    { src: "/images/mZjUp8tYWs6fHWae.png" },
    "H",
  ],
  [
    "H",
    { src: "/images/kxjuTJf3xAAe5yTf.png" },
    { src: "/images/mi2TKWYM_FGuYfWz.png" },
    "H",
    { src: "/images/7tH3ba-e74zEbr2B.png" },
    { src: "/images/FTKTbcjU_dSd4ELT.png" },
    "H",
    { src: "/images/fdrDDa-R-WTFpdtJ.png" },
    { src: "/images/xBu3tDpGjjhjR27B.png" },
  ],
  ["H", "H", "H", "H", "H", "H", "H", "H", "H"],
  [
    { src: "/images/PauEnBcbXDSy-3GF.png" },
    { src: "/images/FTKTbcjU_dSd4ELT.png" },
    "H",
    { src: "/images/mZjUp8tYWs6fHWae.png" },
    { src: "/images/fdrDDa-R-WTFpdtJ.png" },
    "H",
    { src: "/images/dyT3ksKEBSB8Q4pt.png" },
    { src: "/images/kxjuTJf3xAAe5yTf.png" },
    "H",
  ],
  [
    "H",
    { src: "/images/mi2TKWYM_FGuYfWz.png" },
    { src: "/images/7tH3ba-e74zEbr2B.png" },
    "H",
    { src: "/images/mZjUp8tYWs6fHWae.png" },
    { src: "/images/dyT3ksKEBSB8Q4pt.png" },
    { src: "/images/FTKTbcjU_dSd4ELT.png" },
    "H",
    "H",
  ],
  [
    "H",
    "H",
    { src: "/images/fdrDDa-R-WTFpdtJ.png" },
    "H",
    { src: "/images/mi2TKWYM_FGuYfWz.png" },
    "H",
    "H",
    "H",
    { src: "/images/mZjUp8tYWs6fHWae.png" },
  ],
  [
    "H",
    "H",
    "H",
    { src: "/images/FTKTbcjU_dSd4ELT.png" },
    "H",
    "H",
    { src: "/images/mi2TKWYM_FGuYfWz.png" },
    { src: "/images/dyT3ksKEBSB8Q4pt.png" },
    "H",
  ],
];
