import { assetUrl } from "~/lib/assetUrl";

export type NanCell = "H" | { src: string };

/** 旧 nanpure.html の盤面（H = 入力マス） */
export const NANPURE_LAYOUT: NanCell[][] = [
  [
    "H",
    { src: assetUrl("images/mZjUp8tYWs6fHWae.png") },
    { src: assetUrl("images/dyT3ksKEBSB8Q4pt.png") },
    "H",
    "H",
    { src: assetUrl("images/fdrDDa-R-WTFpdtJ.png") },
    "H",
    "H",
    "H",
  ],
  [
    { src: assetUrl("images/7tH3ba-e74zEbr2B.png") },
    "H",
    "H",
    "H",
    { src: assetUrl("images/kxjuTJf3xAAe5yTf.png") },
    "H",
    { src: assetUrl("images/fdrDDa-R-WTFpdtJ.png") },
    "H",
    "H",
  ],
  [
    "H",
    "H",
    { src: assetUrl("images/FTKTbcjU_dSd4ELT.png") },
    { src: assetUrl("images/dyT3ksKEBSB8Q4pt.png") },
    { src: assetUrl("images/PauEnBcbXDSy-3GF.png") },
    "H",
    { src: assetUrl("images/7tH3ba-e74zEbr2B.png") },
    { src: assetUrl("images/mZjUp8tYWs6fHWae.png") },
    "H",
  ],
  [
    "H",
    { src: assetUrl("images/kxjuTJf3xAAe5yTf.png") },
    { src: assetUrl("images/mi2TKWYM_FGuYfWz.png") },
    "H",
    { src: assetUrl("images/7tH3ba-e74zEbr2B.png") },
    { src: assetUrl("images/FTKTbcjU_dSd4ELT.png") },
    "H",
    { src: assetUrl("images/fdrDDa-R-WTFpdtJ.png") },
    { src: assetUrl("images/xBu3tDpGjjhjR27B.png") },
  ],
  ["H", "H", "H", "H", "H", "H", "H", "H", "H"],
  [
    { src: assetUrl("images/PauEnBcbXDSy-3GF.png") },
    { src: assetUrl("images/FTKTbcjU_dSd4ELT.png") },
    "H",
    { src: assetUrl("images/mZjUp8tYWs6fHWae.png") },
    { src: assetUrl("images/fdrDDa-R-WTFpdtJ.png") },
    "H",
    { src: assetUrl("images/dyT3ksKEBSB8Q4pt.png") },
    { src: assetUrl("images/kxjuTJf3xAAe5yTf.png") },
    "H",
  ],
  [
    "H",
    { src: assetUrl("images/mi2TKWYM_FGuYfWz.png") },
    { src: assetUrl("images/7tH3ba-e74zEbr2B.png") },
    "H",
    { src: assetUrl("images/mZjUp8tYWs6fHWae.png") },
    { src: assetUrl("images/dyT3ksKEBSB8Q4pt.png") },
    { src: assetUrl("images/FTKTbcjU_dSd4ELT.png") },
    "H",
    "H",
  ],
  [
    "H",
    "H",
    { src: assetUrl("images/fdrDDa-R-WTFpdtJ.png") },
    "H",
    { src: assetUrl("images/mi2TKWYM_FGuYfWz.png") },
    "H",
    "H",
    "H",
    { src: assetUrl("images/mZjUp8tYWs6fHWae.png") },
  ],
  [
    "H",
    "H",
    "H",
    { src: assetUrl("images/FTKTbcjU_dSd4ELT.png") },
    "H",
    "H",
    { src: assetUrl("images/mi2TKWYM_FGuYfWz.png") },
    { src: assetUrl("images/dyT3ksKEBSB8Q4pt.png") },
    "H",
  ],
];
